In [157]:
#Data Processing
#Practical 1 - Handling Missing Values(Mean Imputation)
import pandas as pd
from sklearn.impute import SimpleImputer

In [158]:
data = {
    'Age':[25,30,None,35],
    'Salary':[40000,None,50000,60000]
}
df = pd.DataFrame(data)

In [159]:
imputer = SimpleImputer(strategy='mean')
df[:] = imputer.fit_transform(df)

In [160]:
print(df)

    Age   Salary
0  25.0  40000.0
1  30.0  50000.0
2  30.0  50000.0
3  35.0  60000.0


In [161]:
#Practical No 2- Dropping Missing Values
import pandas as pd

In [162]:
df = pd.DataFrame({'A':[1,2,None], 'B':[4,None,6]})

In [163]:
df.dropna(inplace=True)
print(df)

     A    B
0  1.0  4.0


In [164]:
#Practical No 3 - Encoding Categorical Data (Label Encoding->Converts text to numbers)
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [165]:
df = pd.DataFrame({
    'City':['Pune','Mumbai','Delhi']
})

In [166]:
le = LabelEncoder()
df['City'] = le.fit_transform(df['City'])

In [167]:
print(df)

   City
0     2
1     1
2     0


In [168]:
#Practical No 4- One Hot Encoding (Converts text into number[binary columns])
import pandas as pd

In [169]:
df = pd.DataFrame({
    'Color':['Red','Blue','Green']
})

In [170]:
encoded = pd.get_dummies(df).astype(int)
print(encoded)

   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           1            0          0
2           0            1          0


In [171]:
# Practical No 5- Feature Scaling (Standardization-Mean=0, Standard deviation=1)(scales the data)
from sklearn.preprocessing import StandardScaler
import numpy as np

In [172]:
X = np.array([[10],[20],[30],[40]])
scaler = StandardScaler()

In [173]:
X_scaled = scaler.fit_transform(X)

In [174]:
print(X_scaled)
#scales values between -1 and +1

[[-1.34164079]
 [-0.4472136 ]
 [ 0.4472136 ]
 [ 1.34164079]]


In [175]:
# Practical No 6- Feature Scaling(Normalization-values between 0 and 1)
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [176]:
X = np.array([[100], [200], [300]])

In [177]:
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)

In [178]:
print(X_norm)
#scales values between 0 and 1

[[0. ]
 [0.5]
 [1. ]]


In [179]:
#Practical 7 on Splitting Dataset
from sklearn.model_selection import train_test_split
import numpy as np

In [180]:
X = np.array([[1], [2], [3], [4]])
y = np.array([0,0,1,1])

In [181]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=1)

In [182]:
print(X_train,X_test)
#separates training and testing data

[[3]
 [1]
 [2]] [[4]]


In [183]:
#Practical No 8 Mini Preprocessing
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [184]:
df = pd.DataFrame({'Age':[25,None,30], 'City':['Pune', 'Mumbai','Delhi']})

In [185]:
df['Age'].fillna(df['Age'].mean(),inplace=True)


C:\Users\shahe\AppData\Local\Temp\ipykernel_33692\1275544653.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)


In [186]:
le = LabelEncoder()
df['City'] = le.fit_transform(df['City'])

In [187]:
print(df)

    Age  City
0  25.0     2
1  27.5     1
2  30.0     0


In [188]:
scaler = StandardScaler()
df[['Age']] = scaler.fit_transform(df[['Age']])
print(df)

        Age  City
0 -1.224745     2
1  0.000000     1
2  1.224745     0


In [223]:
# Normalization using Min–Max Scaling
from sklearn.preprocessing import MinMaxScaler
import numpy as np
# Sample dataset
data = np.array([[10], [20], [30], [40], [50]])
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(data)
print("Original Data:\n", data)
print("Normalized Data:\n", normalized_data)

Original Data:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Normalized Data:
 [[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [227]:
#Standardization using Standard Scaler
from sklearn.preprocessing import StandardScaler
import numpy as np
# Sample dataset
data = np.array([[100], [20], [300], [440], [560]])
scaler = StandardScaler()
standardized_data = scaler.fit_transform(data)
print("Original Data:\n", data)
print("Standardized Data:\n", standardized_data)


Original Data:
 [[100]
 [ 20]
 [300]
 [440]
 [560]]
Standardized Data:
 [[-0.91022212]
 [-1.30597087]
 [ 0.07914975]
 [ 0.77171006]
 [ 1.36533318]]


In [229]:
#Feature Scaling on Multiple Columns (Real Dataset Style)
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# Sample dataset
data = {
    'Age': [22, 25, 47, 52, 46],
    'Salary': [25000, 27000, 55000, 48000, 52000]
}
df = pd.DataFrame(data)
print("Original Data:\n", df)
# Min-Max Scaling
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)
print("\nNormalized Data:\n", df_scaled)


Original Data:
    Age  Salary
0   22   25000
1   25   27000
2   47   55000
3   52   48000
4   46   52000

Normalized Data:
 [[0.         0.        ]
 [0.1        0.06666667]
 [0.83333333 1.        ]
 [1.         0.76666667]
 [0.8        0.9       ]]


In [231]:
#Train-Test Split + Feature Scaling (Best Practice)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

data = {
    'Age': [22, 25, 47, 52, 46, 56, 48],
    'Salary': [25000, 27000, 55000, 48000, 52000, 60000, 58000],
    'Purchased': [0, 0, 1, 1, 1, 0, 1]
}
df = pd.DataFrame(data)
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

print("X_train_scaled:\n", X_train_scaled)
print("\nX_test_scaled:\n", X_test_scaled)


X_train_scaled:
 [[ 0.60647843  0.13454077]
 [-1.6678157  -1.63370936]
 [ 0.90971765  1.05710606]
 [ 0.15161961  0.44206253]]

X_test_scaled:
 [[ 0.30323922  0.90334518]
 [ 0.22742941  0.67270386]
 [-1.44038628 -1.47994848]]


In [233]:
#Feature Scaling using Iris Dataset

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load dataset
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)

print("Original Data (First 5 rows):\n", df.head())

# Standardization
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)

print("\nStandardized Data (First 5 rows):\n", scaled_data[:5])


Original Data (First 5 rows):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Standardized Data (First 5 rows):
 [[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


In [ ]:
'''
In the Wine dataset from scikit-learn, the labels class_0, class_1, and class_2 represent three different cultivars (types/varieties) of wine.

The dataset was originally collected from wines produced in the same region of Italy but from different grape cultivars.

Each class corresponds to one cultivar:

Class 0 → Wines from cultivar A (59 samples)

Class 1 → Wines from cultivar B (71 samples)

Class 2 → Wines from cultivar C (48 samples)

The dataset doesn’t name the cultivars explicitly (they’re anonymized as 0, 1, 2), but the features describe chemical properties of the wine such as 
alcohol content, malic acid, ash, magnesium, flavonoids, color intensity, and so on.

So when you train a classifier on this dataset, the goal is to predict which cultivar (class 0, 1, or 2) a wine belongs to based on its chemical 
composition.
'''

In [237]:
#Normalization using Wine Dataset

from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

data = load_wine()
df = pd.DataFrame(data.data, columns=data.feature_names)

print("Original Data (First 5 rows):\n", df.head())
#178 samples
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(df)

print("\nNormalized Data (First 5 rows):\n", normalized_data[:5])


Original Data (First 5 rows):
    alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines

In [259]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load dataset
df = pd.read_csv("data.csv")

# Separate features and target
X = df.drop('Purchased', axis=1)   # Features
y = df['Purchased']                # Target

# Apply OneHotEncoder to categorical column and StandardScaler to numeric columns
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), ['Country']),       # Encode categorical
        ('scaler', StandardScaler(), ['Age', 'Salary']) # Scale numerical
    ]
)

X_processed = ct.fit_transform(X)
print("Processed Data:\n", X_processed)


Processed Data:
 [[ 1.          0.          0.          0.71993143  0.71101276]
 [ 0.          0.          1.         -1.62367514 -1.36437583]
 [ 0.          1.          0.         -1.21009751 -0.84552869]
 [ 0.          0.          1.         -0.10722383 -0.24020701]
 [ 0.          1.          0.          0.16849459         nan]
 [ 1.          0.          0.         -0.52080146 -0.49963059]
 [ 0.          0.          1.                 nan -1.01847774]
 [ 1.          0.          0.          1.27136827  1.31633443]
 [ 0.          1.          0.          1.54708669  1.66223253]
 [ 1.          0.          0.         -0.24508304  0.27864014]]


In [257]:
#Following is the dataset with columns Country, Age, Salary, and Purchased. You apply a ColumnTransformer that uses OneHotEncoder on Country 
#and StandardScaler on Age and Salary, then train a Logistic Regression model.
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression

# Step 1: Create dataset
data = {
    'Country': ['France', 'Spain', 'Germany', 'Spain', 'France', 'Germany', 'France'],
    'Age': [22, 25, 47, 52, 46, 56, 48],
    'Salary': [25000, 27000, 55000, 48000, 52000, 60000, 58000],
    'Purchased': [0, 0, 1, 1, 1, 0, 1]
}
df = pd.DataFrame(data)

# Step 2: Split features and target
X = df.iloc[:, :-1]   # Country, Age, Salary
y = df.iloc[:, -1]    # Purchased

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0
)

# Step 4: Preprocessing (Encoding + Scaling)
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), ['Country']),       # Encode categorical
        ('scaler', StandardScaler(), ['Age', 'Salary']) # Scale numerical
    ]
)

X_train_processed = ct.fit_transform(X_train)
X_test_processed = ct.transform(X_test)

# Step 5: Train model
model = LogisticRegression()
model.fit(X_train_processed, y_train)

# Step 6: Evaluate
print("Accuracy:", model.score(X_test_processed, y_test))


Accuracy: 0.6666666666666666
